Update

diff --git a/.github/workflows/pkgdown.yaml b/.github/workflows/pkgdown.yaml
--- a/.github/workflows/pkgdown.yaml
+++ b/.github/workflows/pkgdown.yaml
@@ -288,24 +288,19 @@ jobs:
         id: branch-names
         uses: tj-actions/branch-names@v6
 
-      - name: Get latest release 🚀
-        id: get-latest-release
-        uses: pozetroninc/github-action-get-latest-release@v0.7.0
-        with:
-          repository: ${{ github.repository }}
-          excludes: prerelease, draft
-          token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Get branch names 🌿
+        id: branch-names
+        uses: tj-actions/branch-names@v6
 
       - name: Show latest release 🚀
         id: show-latest-release
         run: |
-          echo "Latest release = ${{ steps.get-latest-release.outputs.release }}"
           echo "Current tag = ${{ steps.branch-names.outputs.tag }}"
-          if [[ "${{ steps.branch-names.outputs.tag }}" == "${{ steps.get-latest-release.outputs.release }}" ]]; then
-            echo "Uploading assets to latest release."
-            echo "latest-release-created=true" >> $GITHUB_OUTPUT
+          if [[ $(gh release view ${{ steps.branch-names.outputs.tag }} || true) == "release not found" ]]; then
+            echo "Release not found."
           else
-            echo "Release has not been created for the tag, therefore the assets will not be uploaded."
+            echo "Release found."
+            echo "latest-release-created=true" >> $GITHUB_OUTPUT
           fi
 
       - name: Upload binaries to release ⤴
