Test

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -78,8 +78,8 @@ jobs:
           echo "logical condition: ${{ steps.rc-tag.outputs.is-rc-tag == 'false' || inputs.create-rc-releases == 'true' }}"
           echo "logical condition: ${{ steps.rc-tag.outputs.is-rc-tag == 'false' || inputs.create-rc-releases == true }}"
           echo "Current tag = ${{ steps.branch-name.outputs.tag }}"
-          echo "Release found: $(gh release view ${{ steps.branch-name.outputs.tag }} || true)"
-          if [[ "$(gh release view ${{ steps.branch-name.outputs.tag }} || true)" == "release not found" ]]; then
+          echo "Release found: $(echo "$(gh release view ${{ steps.branch-name.outputs.tag }} || true)" | tr -d '\n')"
+          if [[ "$(echo "$(gh release view ${{ steps.branch-name.outputs.tag }} || true)" | tr -d '\n')" == "release not found" ]]; then
             echo "Release not found."
           else
             echo "Release found."
