Test

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -77,6 +77,13 @@ jobs:
           echo "create rc releases: ${{ inputs.create-rc-releases }}"
           echo "logical condition: ${{ steps.rc-tag.outputs.is-rc-tag == 'false' || inputs.create-rc-releases == 'true' }}"
           echo "logical condition: ${{ steps.rc-tag.outputs.is-rc-tag == 'false' || inputs.create-rc-releases == true }}"
+          echo "Current tag = ${{ steps.branch-name.outputs.tag }}"
+          if [[ "$(gh release view ${{ steps.branch-name.outputs.tag }} || true)" == "release not found" ]]; then
+            echo "Release not found."
+          else
+            echo "Release found."
+            echo "latest-release-created=true" >> $GITHUB_OUTPUT
+          fi
 
       - name: Create release 🌟
         if: >-
