Set LANG: en_US.UTF-8 to fix locale issue in rocker (#228)
See https://github.com/r-lib/styler/issues/1199 and
https://github.com/rocker-org/rocker-versioned2/pull/802 for reference.

This adds the `LANG=en_US.UTF-8` environment variable in the event that
it is not set.

diff --git a/.github/workflows/roxygen.yaml b/.github/workflows/roxygen.yaml
--- a/.github/workflows/roxygen.yaml
+++ b/.github/workflows/roxygen.yaml
@@ -150,6 +150,8 @@ jobs:
           }
         shell: Rscript {0}
         working-directory: ${{ github.event.repository.name }}/${{ inputs.package-subdirectory }}
+        env:
+          LANG: en_US.UTF-8
 
       - name: Roxygen check 🅾
         run: |
@@ -163,19 +165,17 @@ jobs:
             # Attempt to commit and push man-page updates
             if [ "${AUTO_UPDATE}" == "true" ]
             then {
-              # TODO: Disable Roxygen auto-updates until unicode issues are fixed
-              :
-              #echo "Regenerating man pages via auto-update"
-              #git config --global user.name "github-actions"
-              #git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-              #git config pull.rebase false
-              #BRANCH_NAME="${{ steps.branch-name.outputs.head_ref_branch }}"
-              #git pull origin ${BRANCH_NAME} || true
-              #git add -A man/ DESCRIPTION
-              #git commit -m "[skip roxygen] [skip vbump] Roxygen Man Pages Auto Update"
-              #git push -v origin HEAD:${BRANCH_NAME} || \
-              #  (echo "⚠️ Could not push to ${BRANCH_NAME} on $(git remote -v show -n origin | grep Push)" && \
-              #  AUTO_UPDATE=failed)
+              echo "Regenerating man pages via auto-update"
+              git config --global user.name "github-actions"
+              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+              git config pull.rebase false
+              BRANCH_NAME="${{ steps.branch-name.outputs.head_ref_branch }}"
+              git pull origin ${BRANCH_NAME} || true
+              git add -A man/ DESCRIPTION
+              git commit -m "[skip roxygen] [skip vbump] Roxygen Man Pages Auto Update"
+              git push -v origin HEAD:${BRANCH_NAME} || \
+                (echo "⚠️ Could not push to ${BRANCH_NAME} on $(git remote -v show -n origin | grep Push)" && \
+                AUTO_UPDATE=failed)
             }
             fi
             # If auto-update is disabled or is unsuccessful, let 'em know to fix manually
